export default function TermsOfService() {


  return <div className="container py-12 text-lg">
    <h2 className=" text-center text-5xl mb-8">Terms of Service</h2>

    <p>Hello and welcome! These Terms of Service (“Terms”) are an agreement formed between you (“You”) and Moonbox Limited. (“Company,” “Moonbox,” “we” or “us”) and cover the website available at moonbox.com (the “Website”), and the related applications (the “App”) operated on behalf of Moonbox, and together with any content, tools, features and functionality offered on or through our Website and App (the “Services”).</p>

    <p>These Terms govern your access to and use of the Services. Please read them carefully, as they include important information about your legal rights. By accessing and/or using the Services, you’re agreeing to these Terms. If you don’t understand or agree to these Terms, please don’t use the Services.</p>

    <p>For purposes of these Terms, “you” and “your” means you as the user of the Services. If you use the Services on behalf of a company or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity’s behalf.</p>
    <p>Note: these Terms contain an arbitration clause and class action waiver. By agreeing to these Terms, you agree (a) to resolve all disputes with us through binding individual arbitration, which means that you waive any right to have those disputes decided by a judge or jury, and (b) that you waive your right to participate in class actions, class arbitrations, or representative actions. You have the right to opt-out of arbitration as explained below.</p>

    <h3 className=" text-3xl my-4">Use of the Services</h3>
    Your Registration Obligations. You may be required to submit a registration form in order to access and use certain features of the Services. If you choose to register, you agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the Services’ registration form. Registration data and certain other information about you are governed by our Privacy Policy.

    Member Account, Password and Security. You are responsible for maintaining the confidentiality of your password and account, if any, and are fully responsible for any and all activities that occur under your password or account. You agree to (a) immediately notify Moonbox of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session when accessing the Services. Moonbox will not be liable for any loss or damage arising from your failure to comply with this paragraph.

    Modifications to Site. Moonbox reserves the right to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice. You agree that Moonbox will not be liable to you or to any third party for any modification, suspension or discontinuance of the Services.

    General Practices Regarding Use and Storage. You acknowledge that Moonbox may establish general practices and limits concerning use of the Services, including without limitation the maximum period of time that data or other content will be retained by the Services and the maximum storage space that will be allotted on Moonbox’s servers on your behalf. You agree that Moonbox has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded to the Services. You acknowledge that Moonbox reserves the right to terminate accounts that are inactive for an extended period of time. You further acknowledge that Moonbox reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.

    <h3 className=" text-3xl my-4">Conditions Of Use</h3>

    User Conduct. In addition to agreeing to comply with our Acceptable Use Policy (“AUP”), which is incorporated herein, you agree to comply with the following conditions in using the Services. You are solely responsible for all code, video, images, information, data, text, software, music, sound, photographs, graphics, messages or other materials (“Content”) that you upload, post, publish or display (hereinafter, “Upload”) or email or otherwise transmit via the Services. Your use of the Services may also be subject to license and use restrictions set forth in the Creative ML Open RAIL-M License. The following are examples of the kind of Content and/or use that is illegal or prohibited by Moonbox. Moonbox reserves the right to investigate and take appropriate legal action against anyone who, in Moonbox’s sole discretion, violates this provision, including without limitation, removing the offending Content from the Website or Services, suspending or terminating the account of such violators and reporting them to applicable law enforcement authorities.
    You agree to not use the Website or Services to:
    upload or transmit any Content that: 

    (i) infringes any intellectual property or other proprietary rights of any party; 

    (ii) you do not have a right to upload under any law or under contractual or other relationships; 

    (iii) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; 

    (iv) poses or creates a privacy or security risk to any person; 

    (v) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” “contests,” “sweepstakes,” or any other form of solicitation; 

    (vi) is unlawful, harmful, threatening, abusive, harassing, tortious, excessively violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another’s privacy, hateful racially, ethnically or otherwise objectionable;

    (vii) in the sole judgment of Moonbox, is objectionable or which restricts or inhibits any other person from using or enjoying the Website or Services, or which may expose Moonbox or its users to any harm or liability of any type;

    interfere with or disrupt the Website or Services or servers or networks connected to the Website or Services, or disobey any requirements, procedures, policies or regulations of networks connected to the Website or Services;

    violate any applicable local, national or international law, or any regulations having the force of law;

    impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;

    solicit personal information from anyone under the age of 18;

    harvest or collect email addresses or other contact information of other users from the Website or Services by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;

    advertise or offer to sell or buy any goods or services for any business purpose that is not specifically authorized;

    further or promote any criminal activity or enterprise or provide instructional information about illegal activities;

    obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Website or Services;
    lease, lend, sell or sublicense any part of the Services;
    try to get around any technological measure designed to protect the Services or any technology associated with the Services;

    reverse engineer, disassemble, decompile, decode, adapt, or otherwise attempt to derive or gain access to any Services source code, in whole or in part (unless a portion of code contained within the Services is released as open source and the open source license governing such code expressly permits reverse engineering, copying or other modification)
    use the Services to create malicious or abusive content (as determined by Moonbox in its sole discretion) or any content that violates a Moonbox policy; or use the Services (or any part thereof or any technology contained therein) in any manner that infringes, misappropriates, or otherwise violates any intellectual property right or other right of any person, or that violates any applicable laws.

    <h3 className=" text-3xl my-4">Intellectual Property Rights</h3>

    User Content Uploaded to the Site. With respect to the content or other materials you upload to or create using the Services (collectively, “User Content”), you represent and warrant that you own all right, title and interest in and to such User Content, including, without limitation, all copyrights and rights of publicity contained therein, or are otherwise permitted to use them for the applicable purposes, for example by license or legal exception or limitation. By creating or uploading any User Content you own or create using the Service, you retain all rights in it (to the extent you would otherwise hold such rights) and hereby grant and will grant Moonbox to the fullest extent permitted under the law a nonexclusive, worldwide, royalty-free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use your User Content for any Moonbox-related purpose in any form, medium or technology now known or later developed.
    Characters and Generations. For any automated AI character (&quot;Character&quot;) that you create or upload using the Service, you own all rights in that Character (and to the extent you create derivative works, you own all rights you otherwise would own in them) and any text, images or video it generates (&quot;Generations&quot;) that are elicited directly or indirectly by you, and grant to Moonbox and to any Moonbox user who elicits Generations from your Character to the fullest extent permitted under the law a nonexclusive, worldwide, royalty-free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use the Character you created and any related Generations for any purpose in any form, medium or technology now known or later developed. As to a user interacting with a Character created or uploaded by another user or created or uploaded by Moonbox, the user who elicits the Generations from a Character owns all rights in those Generations and grants to both Moonbox and the creator(s) of the applicable Character a nonexclusive, worldwide, royalty-free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use any Generations. For avoidance of doubt, violations of Moonbox&apos;s Acceptable Use Policy unrelated to intellectual property issues does not affect the user&apos;s intellectual property rights in any Characters or their Generations.
    Website or Services Content, Software and Trademarks. You acknowledge and agree that the Website or Services may contain content or features (“Site Content”) that are protected by copyright, patent, trademark, trade secret or other proprietary rights and laws. In connection with your use of the Website or Services you will not engage in or use any data mining, robots, scraping or similar automated data gathering or extraction methods. If you are blocked by Moonbox from accessing the Website or Services (including by blocking your IP address), you agree not to implement any measures to circumvent such blocking (e.g., by masking your IP address or using a proxy IP address). Any use of the Website or Services, or the Site Content, other than as specifically authorized herein is strictly prohibited. Any rights not expressly granted herein are reserved by Moonbox.
    The Moonbox name and logos are trademarks of Moonbox(collectively the “Moonbox Trademarks”). Other trademarks used and displayed via the Website or Services may be trademarks of their respective owners who may or may not endorse or be affiliated with or connected to Moonbox. Nothing in these Terms or the Website or Service should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of Moonbox Trademarks without our prior written permission in each instance.
    Third Party Material. Under no circumstances will Moonbox be liable in any way for any content or materials of any third parties, including character bots created by third parties and any Generations resulting from such character bots, including, but not limited to infringement of intellectual property rights, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content. You acknowledge that Moonbox does not pre-screen content, but that Moonbox and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Website or Services. Without limiting the foregoing, Moonbox and its designees will have the right to remove any content that violates these Terms, our AUP, or is deemed by Moonbox, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content.
    You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Website or Services (“Submissions”) provided by you to Moonbox are non-confidential and Moonbox will be entitled to the unrestricted use and dissemination of these Submissions for any purpose, without acknowledgment of or compensation to you.
    Without limiting the foregoing, you acknowledge and agree that Moonbox may preserve content and may also disclose content and/or metadata if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce these Terms; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of Moonbox, its users and the public. You understand that the technical processing and transmission of the Website and Services, including your content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.
    Copyright Complaints. Moonbox respects the intellectual property of others, and we ask our users to do the same. If you believe that your work has been copied in a way that constitutes copyright infringement, or that your intellectual property rights have been otherwise violated, you should notify Moonbox of your infringement claim in accordance with the procedure set forth below.
    Moonbox will process and investigate notices of alleged infringement and will take appropriate actions under applicable intellectual property laws with respect to any alleged or actual infringement. A written notification of claimed copyright infringement should be mailed to support@moonbox.com.
    To be effective, the notification must be in writing and contain the following information: an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest; a description of the copyrighted work or other intellectual property that you claim has been infringed; a description of where the material that you claim is infringing is located on the Site, with enough detail that we may find it on the Site; your address, telephone number, and email address; a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law; a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.
    <h3 className=" text-3xl my-4">Third Party Websites and Services</h3>
    The Services may provide, or third parties may provide, links or other access to other sites and resources on the Internet or to third-party applications. Moonbox has no control over such sites, resources or applications and Moonbox is not responsible for and does not endorse such sites, resources or applications. You further acknowledge and agree that Moonbox will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any content, events, goods or services available on or through any such sites, resources or applications. Any dealings you have with third parties found while using the Services are between you and the third party, and you agree that Moonbox is not liable for any loss or claim that you may have against any such third party.

    <h3 className=" text-3xl my-4">Indemnity and Release</h3>
    You agree to release, indemnify and hold Moonbox and its affiliates and their officers, employees, directors and agents harmless from any from any and all losses, damages, expenses, including reasonable attorneys’ fees, rights, claims, actions of any kind and injury (including death) arising out of or relating to your use of the Services or any related information, any User Content, your application(s) to Moonbox or the results thereof, your violation of these Terms of Use or your violation of any rights of another.

    <h3 className=" text-3xl my-4">Disclaimer of Warranty</h3>
    Your use of the Service is at your sole risk. The site is provided on an “AS IS” and “AS AVAILABLE” basis. Moonbox expressly disclaims all warranties of any kind, whether express, implied or statutory, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose, title and non-infringement. Moonbox makes no warranty that (i) the Services will meet your requirements, (ii) the Services will be uninterrupted, timely, secure, or error-free, or (iii) the results that may be obtained from the use of the Services will be accurate or reliable.

    <h3 className=" text-3xl my-4">Limitation of Liability</h3>
    You expressly understand and agree that Moonbox will not be liable for any indirect, incidental, special, consequential, exemplary damages, or damages for loss of profits including but not limited to, damages for loss of goodwill, use, data or other intangible losses (even if Moonbox has been advised of the possibility of such damages), whether based on contract, tort, negligence, strict liability or otherwise, resulting from: (I) the use or the inability to use the Services or any related information; (ii) unauthorized access to or alteration of your transmissions or data; (iii) statements or conduct of any third party (including users) on the Services; or (iv) any other matter relating to the Services.

    Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations set forth above may not apply to you. If you are dissatisfied with any portion of the site or with these terms of use, your sole and exclusive remedy is to discontinue use of the Services.

    <h3 className=" text-3xl my-4">Termination</h3>
    You agree that Moonbox, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the Services and remove and discard any content within the Website or Services, for any reason, including, without limitation, for lack of use or if Moonbox believes that you have violated or acted inconsistently with the letter or spirit of these Terms or Moonbox’s Acceptable Use Policy. Moonbox may also in its sole discretion and at any time discontinue providing the Services, or any part thereof, with or without notice. You agree that any termination of your access to the Services under any provision of these Terms or our AUP may be effected without prior notice, and acknowledge and agree that Moonbox may (but has no obligation to) immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Services. Termination of your account or access to any component of the Services will not terminate Moonbox’s rights to your User Content. Further, you agree that Moonbox will not be liable to you or any third party for any termination of your access to the Services.

    <h3 className=" text-3xl my-4">General</h3>
    Entire Agreement. These Terms constitute the entire agreement between you and Moonbox and govern your use of our Services, superseding any prior agreements between you and Moonbox with respect to the Services.
    Severance. If any provision of these Terms is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties’ intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect.
    No Waiver. Any failure of Moonbox to exercise or enforce any right or provision of these Terms does not constitute a waiver of such right or provision.

    Expiration of Claims. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Site or these Terms of Use must be filed within one (1) year after such claim or cause of action arose or be forever barred.
    Admissibility. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
    Assignment. You may not assign these Terms without the prior written consent of Moonbox, but Moonbox may assign or transfer these Terms of Use, in whole or in part, without restriction.
    Section Headings. The section titles in these Terms of Use are for convenience only and have no legal or contractual effect.
    Notice. Notices to you may be made via either email or regular mail. The Site may also provide notices to you of changes to these Terms or other matters by displaying notices or links to notices generally on the Website.

    <h3 className=" text-3xl my-4">Changes to these Terms</h3>
    We reserve the right, at our sole discretion, to change or modify portions of these Terms at any time. If we do this, we will post the changes on this page and will indicate at the top of this page the date these terms were last revised. Any such changes will become effective no earlier than fourteen (14) days after they are posted, except that changes addressing new functions of the Site or changes made for legal reasons will be effective immediately. Your continued use of the Site after the date any such changes become effective constitutes your acceptance of the new Terms.

    <h3 className=" text-3xl my-4">Contact Us</h3>
    If you have any questions about our Services, or to report any violations of these Terms or our Acceptable Use Policies, please contact us at support@moonbox.com.
  </div>
}